version: '3.4'
services:
  
  pdsphenotypemapping:
    build:
      context: .
    restart: always
    environment:
      PDSDPI_HOST: $PDSDPI_HOST
      PDSDPI_PORT: $PDSDPI_PORT
    ports:
      - $PDSPHENOTYPEMAPPING_PORT:8080

    
