openapi: 3.0.0
info:
  description: 
    This is a pds mapper plugin api.
  version: "2.0.0"
  title: pdspi-mapper-example
  license:
    name: MIT
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /mapping:
    post:
      summary: map from patient record to clinical feature variables
      operationId: api.mappingClinicalFromData
      parameters:
        - in: query
          name: patient_id
          example: 38
          schema:
            type: string
          required: true
        - in: query
          name: timestamp
          schema:
            type: string
            format: date-time
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PatientVariableTypesAndData"
      responses: # has to match output of dispatcher.py
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PatientVariables'
        '400':
          description: Invalid input
        '500':
          description: Internal server error
components:
  schemas:
    PatientVariableTypes:
      type: array
      items:
        $ref: "#/components/schemas/PatientVariableType"
    PatientVariableTypesAndData:
      type: object
      properties:
        patientVariables:
          $ref: "#/components/schemas/PatientVariableTypes"
        data:
          type: object
          description: a FHIR bundle
      required:
        - patientVariables
        - data
      additionalProperties: false
    PatientVariables:
      type: array
      items:
        $ref: "#/components/schemas/PatientVariable"
    PatientVariable:
      type: object
      required:
        - value
        - units
        - certitude
        - how
        - variableType
      properties:
        value:
          type: string
          description: the actual value of the patient variable. If 'pds-retrieve-datum' then retrieve from patient data warehouse, otherwise use the value as-is
          example: "0.5"
        units:
          type: string
          description: "The unit is standard throughout the pds system. It's up to the guidance plugin to make unit conversions as needed by the guidance model, just as it is up to the dashboard to make unit conversions as needed by the end user."
          example: "years"
        certitude:
          type: int
          description: The certitude of the value, 0 not certain, 1 somewhat certain, 2 certain
          example: 2
        how:
          type: string
          description: "If the variable is 'pds-retrieve-datum', then 'how' will read 'The value was specified by the end user.'"
          example: "The value was specified by the end user."
        variableType:
          $ref: '#/components/schemas/PatientVariableType'
      additionalProperties: false
    PatientVariableType:
      type: object
      required:
        - title
        - clinicalFeatureVariable
        - description
        - why
      properties:
        title:
          type: string
          example: "Age"
        clinicalFeatureVariable:
          type: string
          example: "LOINC:30525-0"
        units:
          type: string
          description: "The unit is standard throughout the pds system. It's up to the guidance plugin to make unit conversions as needed by the guidance model, just as it is up to the dashboard to make unit conversions as needed by the end user."
          example: "years"
        description: 
          type: string
          example: "Age is a floating point number; e.g., a 6 month old child is 0.5 years."
        why:
          type: string
          example: "Age is used to calculate the creatinine clearance. Dosing is lower for geriatric patient and contraindicated for pediatric patients"
      additionalProperties: false
        
