openapi: 3.0.0
info:
  description: 
    This is a pds-phenotype-mapping-plugin.  You can find
    out more about Swagger at
    [http://swagger.io](http://swagger.io) or on
    [irc.freenode.net, #swagger](http://swagger.io/irc/).
  version: "1.0.0"
  title: pds-phenotype-mapping-plugin
  license:
    name: MIT
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: patient
    description: Patient information
    externalDocs:
      description: Find out more
      url: 'http://swagger.io'
paths:
  /mapping:
    get:
      summary: Add patient record directory, patient_id, system and diagnosis code
      operationId: api.mappingClinical
      parameters:
        - in: query
          name: patient_id
          schema:
            type: string
          required: true
        - in: query
          name: clinical_feature_variable
          schema:
            type: string
          required: true
        - in: query
          name: timestamp
          schema:
            type: string
          required: true
      responses: # has to match output of dispatcher.py
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mapping'
        '405':
          description: Invalid input
components:
  schemas:
    Mapping:
      type: object
      properties:
        value: {}
        calculation:
          type: string
        certitude:
          type: integer
